language: python
python:
- '3.6'
sudo: false
before_install:
- docker pull postgres
- docker pull python
- docker build .
script:
- docker-compose up -d
- docker exec -it 20172classificacaoderiscopediatrico_web_1 python manage.py test