sudo: required
language: python
python:
  - '3.6'
services:
  - docker
before_script:
  - docker-compose up --build -d
script:
  - docker-compose run web python manage.py test
after_script:
  - docker-compose down